name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use a stable Python version supported by GitHub Actions
          python-version: "3.12"  # Changed from 3.13 (not yet widely supported)

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests  # Add this if you have tests
        run: pytest      # Or your test command
